spring.datasource.url=jdbc:postgresql://dpg-d1sggpbuibrs73aduv0g-a.oregon-postgres.render.com:5432/mapaereo_db
spring.datasource.username=estevaodev
spring.datasource.password=RxR8mmcsG5m3J8FiN9hrD0XgfvsMt4t8

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
