spring.application.name=my-spring-app
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=20000

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false